### ISSUE TITLE
Support for Graylog 4

### ISSUE THREAD

**Issue by jfgreco** [hidapple/graylog-plugin-teams#101]
I installed the current JAR file but the UI doesn't see it.

**Comment by hidapple** [comment]
Thank you for raising the issue.

You installed this plugin into Graylog v4, right?
I will catch up how the new version of Graylog works and how 3rd party plugins support it.

**Comment by rconte84** [comment]
So, it doesn't work on Graylog 4?

**Comment by plrunner** [comment]
+1 we need support for Graylog 4

**Comment by jfgreco** [comment]
> 
> 
> Thank you for raising the issue.
> 
> You installed this plugin into Graylog v4, right?
> I will catch up how the new version of Graylog works and how 3rd party plugins support it.

Correct. Using the most recent version of Graylog.

**Comment by masonb81** [comment]
+1 Grayling 4 support for this teams notification pluggin would be epic! Cheers for your efforts

**Comment by hidapple** [comment]
I published version 2.0.4 that uses graylog library version 4.x.x.
I confirmed 2.0.4 works with Gralog v4, to be more precise, I tested on Graylog v4.0.7.

But I also confirmed 2.0.3 works on v4.0.7 as well, so if it did not work on Graylog v4, you guys might have another problem. So if you guys still have any problems, please create new issue and describe detailed information. Issue template would be helpful for you to describe your problem.

Thanks!

**Comment by jfgreco** [comment]
Just tested. Confirmed working 4.0.7

**Comment by hidapple** [comment]
Unfortunately, this plugin does not appear on the System / Configurations even if it's installed and works properly.
For now, you can see Graylog system log to confirm if this plugin is installed or not like below.
```
2021-05-24 16:06:59,881 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Microsoft Teams Notification 2.0.4 [org.graylog.plugins.teams.TeamsNotificationPlugin]
```

**Comment by ulfonso** [comment]
Hi, the plugin loaded successfully, but i can not choose it in the dropdownlist.
Any suggestions ?
Thanks
