### ISSUE TITLE
Project depends on Graylog Server/Radio 

### ISSUE THREAD

**Issue by asachs01** [hidapple/graylog-plugin-teams#135]
Howdy @hidapple 👋 

When attempting to use your plugin, I noticed that it has dependencies on Graylog Server and Graylog Radio:

https://github.com/hidapple/graylog-plugin-teams/blob/5327f3b89e902c57579aaa0bb13518c57ff4bb43/src/deb/control/control#L7

This feels like a couple of holdovers from the early days of Graylog--is it possible to remove them, or at least change it to depend on `graylog-server | graylog-enterprise`?

**Comment by hidapple** [comment]
Thank you for your suggestion!
I removed graylog-radio from project dependencies by https://github.com/hidapple/graylog-plugin-teams/pull/136
