### ISSUE TITLE
Message field in backlog not appearing

### ISSUE THREAD

**Issue by BrziHR** [hidapple/graylog-plugin-teams#18]
Hi,

When using the backlog the plugin doesn't output the field named "message".

The same field gets properly printed in various Slack notification plugins.

Example:
```${if backlog}
${foreach backlog message}


**Container Name**: ${message.fields.container_name}
**Host**: ${message.fields.host}
**Message**: ${message.fields.message}
**test**: ${message.fields.timestamp}

${end}${else}<No backlog>
${end}
```

The fields timestamp, container_name and host properly get printed but message does not.

Graylog version:
`Graylog 3.1.3+cda805f (graylog/graylog:3.1.3-2 image from Docker Hub)`

Can you please take a look?

**Comment by hidapple** [comment]
Hi, thank you for reporting the issue.
I think you can get message text from `message.message`.
Please try that.

**Comment by BrziHR** [comment]
Hi,

Yes I can confirm it is obtainable from `message.message`

I've also noticed the same goes for obtaining the `source` field. Do you perhaps have a list of these fields where only `message.` needs to be specified?

**Comment by hidapple** [comment]
`message` object(object inside backlog) has following fields. 
- id(auto generated id)
- index(Elasticsearch index name storing the message)
- message
- timestamp
- source
- stream_ids

[This page](http://docs.graylog.org/en/3.1/pages/streams/alerts.html) may be helpful for you.

**Comment by BrziHR** [comment]
Thanks, that was it.
