### ISSUE TITLE
Migrate to Teams Workflow

### ISSUE THREAD

**Issue by unbearables** [hidapple/graylog-plugin-teams#234]
Microsoft is deprecating webhooks through Connectors and is replacing that with Microsoft Workflows see https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/ - the deadline is 15.8.2024. With this change they introduce API changes see https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=PowerShell%2Ctext1

It would be useful to alter the plugin so it is plug-and-play with this new approach. Since Teams is cloud solution it is pointless to keep the old Connector approach, so it will be a breaking change, but only on client side in Teams (needs to be reconfigured) - the config will remain the same.

I will release new minor version with this.

**Comment by unbearables** [comment]
I will implement this in the nearest future as we are directly impacted by this change.

**Comment by killdashnine** [comment]
+1

**Comment by ibrahimrehman1** [comment]
Thanks for the update. Looking forward to the new release 😊

**Comment by unbearables** [comment]
Change was successfully done and will be released in `2.1.0`.

Note that you might encounter has some issues in formatting as the Teams API changed via AdaptiveCard. For example preformatting text (TextBlock) + collapsing cards no longer works. I recommend using https://adaptivecards.io/designer/ and test your content in `TextBlock` element - see README for more info.

If there is an issue that you think should be covered in this plugin then please open a new issue, this thread will be locked.
