### ISSUE TITLE
installed teams plugins

### ISSUE THREAD

**Issue by anoopswsib** [hidapple/graylog-plugin-teams#46]
Hi there I installed ms teams plugin 2.0.2 but then when i go in graylog notification type I dont see it available in the list. can you let me know what is going wrong

**Comment by hidapple** [comment]
Could you give me more detail information?
- What version of Graylog Web Interface you use?
- Did you find any error logs when you start up Graylog?

**Comment by wrightca** [comment]
I've done the same with 2.0.2 using GL3.2.4. I'm guessing it doesn't work with 3.2 yet?

**Comment by anoopswsib** [comment]
actually i cleaned the cache of browser and now i can see the teams plugin in the notification type

**Comment by wrightca** [comment]
That worked for me too. Thanks @anoopswsib.

**Comment by hidapple** [comment]
Thanks. I'm closing this issue because it seems to be cache problem.
